[2024-02-21T09:21:08.147+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation1.stream_data_from_api scheduled__2024-02-20T00:00:00+00:00 [queued]>
[2024-02-21T09:21:08.159+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation1.stream_data_from_api scheduled__2024-02-20T00:00:00+00:00 [queued]>
[2024-02-21T09:21:08.160+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T09:21:08.176+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2024-02-20 00:00:00+00:00
[2024-02-21T09:21:08.181+0000] {standard_task_runner.py:60} INFO - Started process 171 to run task
[2024-02-21T09:21:08.187+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'user_automation1', 'stream_data_from_api', 'scheduled__2024-02-20T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/kafka_streaming.py', '--cfg-path', '/tmp/tmp8juep21c']
[2024-02-21T09:21:08.192+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask stream_data_from_api
[2024-02-21T09:21:08.276+0000] {task_command.py:423} INFO - Running <TaskInstance: user_automation1.stream_data_from_api scheduled__2024-02-20T00:00:00+00:00 [running]> on host 29f1ae6ea77a
[2024-02-21T09:21:08.422+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='minhduc' AIRFLOW_CTX_DAG_ID='user_automation1' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-02-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-20T00:00:00+00:00'
[2024-02-21T09:21:08.798+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-02-21T09:21:08.799+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2024-02-21T09:21:08.799+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-02-21T09:21:08.813+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-02-21T09:21:08.814+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2024-02-21T09:21:08.920+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-02-21T09:21:08.921+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2024-02-21T09:21:08.922+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-02-21T09:21:09.021+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-02-21T09:21:09.022+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2024-02-21T09:21:09.049+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-02-21T09:21:09.050+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2024-02-21T09:21:09.050+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-02-21T09:21:09.062+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-02-21T09:21:09.063+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2024-02-21T09:21:09.064+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/kafka_streaming.py", line 41, in stream_data
    producer = KafkaProducer(bootstrap_servers=['broker:29092'],max_block_ms = 5000) # Call to broker container when using airflow
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/kafka/producer/kafka.py", line 381, in __init__
    client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-02-21T09:21:09.087+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=user_automation1, task_id=stream_data_from_api, execution_date=20240220T000000, start_date=20240221T092108, end_date=20240221T092109
[2024-02-21T09:21:09.104+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 10 for task stream_data_from_api (NoBrokersAvailable; 171)
[2024-02-21T09:21:09.119+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-21T09:21:09.150+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
